In [1]:
import numpy as np
#Creating array in python using list
mylist = [1,2,3]
arr = np.array(mylist)
arr

array([1, 2, 3])

In [2]:
#2 dimensional array or Matrices.
list = [1,2,3], [4,5,6], [7,8,9]
arr = np.array(list)
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [3]:
#we can create array also using arange() method.
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [4]:
#arange([start,] stop[, step,], dtype=None, *, like=None)
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

In [5]:
#Return a new array of given shape and type, filled with zeros.
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [6]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [7]:
#Return a new array of given shape and type, filled with ones.
np.ones(5)

array([1., 1., 1., 1., 1.])

In [8]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [9]:
#Return evenly spaced numbers over a specified interval.
np.linspace(0,5,10)

array([0.        , 0.55555556, 1.11111111, 1.66666667, 2.22222222,
       2.77777778, 3.33333333, 3.88888889, 4.44444444, 5.        ])

In [10]:
#Return a 2-D array with ones on the diagonal and zeros elsewhere.
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [11]:
#Random values in a given shape.
np.random.rand(5)

array([0.47811617, 0.52983937, 0.47421228, 0.22033205, 0.00316265])

In [12]:
np.random.rand(3,3)

array([[0.83900776, 0.68083052, 0.63144291],
       [0.03272038, 0.86220043, 0.79085422],
       [0.7094986 , 0.92130549, 0.86470168]])

In [13]:
#Return a sample (or samples) from the "standard normal" distribution.
np.random.randn(5)

array([-0.65549626,  1.16888576, -0.9010442 , -0.52110543,  0.84871515])

In [14]:
np.random.randn(4,5)

array([[-0.82621553,  0.7477725 , -1.37497839,  0.73271477,  0.6424373 ],
       [ 0.07856872, -0.37992973, -0.65913543, -0.44490133,  0.74313711],
       [-1.32614809,  0.23979764, -0.31717894,  1.26687988, -0.35220322],
       [-1.53066423,  1.83584469, -1.08477578,  2.63209385, -0.53413699]])

In [15]:
ranarr = np.random.randint(0,50,10)
ranarr

array([38, 36, 20, 47,  8,  4, 43, 29,  8, 19])

In [16]:
ar = np.arange(25)
ar

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [17]:
ar.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [18]:
ranarr.max()

47

In [19]:
ranarr.min()

4

In [20]:
ar.ravel()#Flattens the array.

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [23]:
#Shows how the two array stack together.
ar1 = np.array([10,11,12,13,14])
ar2 = np.array([15,16,17,18,19])
np.hstack((ar1,ar2))

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [24]:
#Array with empty()
br = np.empty((3,3))
br

array([[0.83900776, 0.68083052, 0.63144291],
       [0.03272038, 0.86220043, 0.79085422],
       [0.7094986 , 0.92130549, 0.86470168]])

In [ ]:
#argmin will return position of min element in an array.
ranarr.argmin()

In [ ]:
#argmax will return position of max element in an array.
ranarr.argmax()

In [ ]:
arra = ar.reshape(5,5)

In [ ]:
arra

In [ ]:
arra.shape

In [ ]:
arra.dtype

In [ ]:
from numpy.random import randint
randint(0,10,5)

# Numpy Indexing and Selection.

In [ ]:
num = np.arange(0,11)
num

In [ ]:
num[8]

In [ ]:
num[0:8]

In [ ]:
num[:]

In [ ]:
num[5:10]

In [ ]:
num[0:5] = 100

In [ ]:
num

In [ ]:
ary = np.arange(0,11)

In [ ]:
ary

In [ ]:
#Copy the element of ary in arr_copy
arr_copy = ary.copy()
arr_copy

In [ ]:
arr_copy[:] = 100


In [ ]:
arr_copy

In [ ]:
ary

# 2-Dimensional array indexing or slicing.

In [ ]:
arr_2d = np.array([[34,566,790, 78, 90], [44,65,63,78,56], [723,843,96,10,90]])
arr_2d

In [ ]:
arr_2d[1][2]                               

In [ ]:
arr_2d[1,2]

In [ ]:
arr_2d[2,2]

In [ ]:
arr_2d[:1, 1:2]

In [ ]:
arr_2d[1:, :2]

In [ ]:
arr_2d[:2, :2]

In [ ]:
arr_2d[1:2, :]

In [ ]:
arr_2d[:]

In [ ]:
arr_2d[1:,1:]

In [ ]:
arr_2d[:2,:]

In [ ]:
aar = np.arange(1,11)
aar

In [ ]:
bool_arr = aar>5

In [ ]:
bool_arr

In [ ]:
aar[bool_arr]

In [ ]:
aar[aar>2]

In [ ]:
aar[aar<5]

In [ ]:
arr_5d = np.arange(50).reshape(5,10)

In [ ]:
arr_5d

In [ ]:
arr_5d[1:, 1:3]

In [ ]:
arr_5d[3:, 6:8]

# Array Operations.

In [ ]:
brr = np.arange(1,11)
brr

In [ ]:
brr + brr

In [ ]:
brr - brr

In [ ]:
brr * brr

In [ ]:
brr / brr

In [ ]:
brr + 100

In [ ]:
np.sqrt(brr)

In [ ]:
brr ** 2

In [ ]:
np.exp(brr)

In [ ]:
brr.max()

In [ ]:
np.sin(brr)

In [ ]:
np.random.randn(25)

In [ ]:
np.linspace(0,1,20)

In [ ]:
mat = np.arange(1,26).reshape(5,5)
mat

In [ ]:
mat[2:, 1:]

In [ ]:
crr = mat[3:4, 4]
crr[0]

In [ ]:
mat[0:3,1:2]

In [ ]:
mat[4, :]

In [ ]:
mat[3:, :]

In [ ]:
np.sum(mat)


In [ ]:
col = np.sum(mat, axis = 0)

In [ ]:
col

In [ ]:
np.std(mat, dtype = np.float64)

In [ ]:
np.std(mat)

In [ ]:
c = np.linspace(0,1,11)
c


In [ ]:
np.arange(1,101).reshape(10,10)/100

In [ ]:
np.random.rand(1)