In [3]:
import numpy as np
#Creating array in python using list
mylist = [1,2,3]
arr = np.array(mylist)
arr

array([1, 2, 3])

In [4]:
#2 dimensional array or Matrices.
list = [1,2,3], [4,5,6], [7,8,9]
arr = np.array(list)
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [5]:
#we can create array also using arange() method.
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [6]:
#arange([start,] stop[, step,], dtype=None, *, like=None)
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

In [7]:
#Return a new array of given shape and type, filled with zeros.
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [8]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [9]:
#Return a new array of given shape and type, filled with ones.
np.ones(5)

array([1., 1., 1., 1., 1.])

In [10]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [11]:
#Return evenly spaced numbers over a specified interval.
np.linspace(0,5,10)

array([0.        , 0.55555556, 1.11111111, 1.66666667, 2.22222222,
       2.77777778, 3.33333333, 3.88888889, 4.44444444, 5.        ])

In [12]:
#Return a 2-D array with ones on the diagonal and zeros elsewhere.
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [13]:
#Random values in a given shape.
np.random.rand(5)

array([0.90049395, 0.3755758 , 0.73399044, 0.41223209, 0.61194996])

In [14]:
np.random.rand(3,3)

array([[0.71515746, 0.51979487, 0.9337218 ],
       [0.69473627, 0.51973701, 0.69105558],
       [0.45583283, 0.29896751, 0.26257237]])

In [15]:
#Return a sample (or samples) from the "standard normal" distribution.
np.random.randn(5)

array([-1.76128792, -0.34608786, -0.1035385 , -2.96554654,  0.8048193 ])

In [16]:
np.random.randn(4,5)

array([[-6.19365220e-01, -1.92055804e+00, -7.82361228e-01,
        -4.38832958e-01, -1.11699214e+00],
       [ 5.50613902e-01, -1.99918022e-02, -1.44477695e+00,
         1.21352869e-01,  1.29875136e+00],
       [-1.34989292e+00, -6.45237257e-02, -1.10807686e-01,
        -2.50512992e-01, -1.91081805e-03],
       [ 5.37348907e-01,  3.60120673e-01, -6.37580794e-01,
         1.59387457e+00,  9.95949379e-01]])

In [17]:
ranarr = np.random.randint(0,50,10)
ranarr

array([ 9, 15, 22, 27, 33, 24, 19,  0,  9, 35])

In [18]:
ar = np.arange(25)
ar

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [19]:
ar.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [20]:
ranarr.max()

35

In [21]:
ranarr.min()

0

In [22]:
#argmin will return position of min element in an array.
ranarr.argmin()

7

In [23]:
#argmax will return position of max element in an array.
ranarr.argmax()

9

In [24]:
arra = ar.reshape(5,5)

In [25]:
arra

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [26]:
arra.shape

(5, 5)

In [27]:
arra.dtype

dtype('int32')

In [28]:
from numpy.random import randint
randint(0,10,5)

array([0, 7, 7, 8, 6])

# Numpy Indexing and Selection.

In [29]:
num = np.arange(0,11)
num

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [30]:
num[8]

8

In [31]:
num[0:8]

array([0, 1, 2, 3, 4, 5, 6, 7])

In [32]:
num[:]

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [33]:
num[5:10]

array([5, 6, 7, 8, 9])

In [34]:
num[0:5] = 100

In [35]:
num

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [36]:
ary = np.arange(0,11)

In [37]:
ary

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [38]:
#Copy the element of ary in arr_copy
arr_copy = ary.copy()
arr_copy

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [39]:
arr_copy[:] = 100


In [40]:
arr_copy

array([100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100])

In [41]:
ary

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

# 2-Dimensional array indexing or slicing.

In [4]:
arr_2d = np.array([[34,566,790, 78, 90], [44,65,63,78,56], [723,843,96,10,90]])
arr_2d

array([[ 34, 566, 790,  78,  90],
       [ 44,  65,  63,  78,  56],
       [723, 843,  96,  10,  90]])

In [5]:
arr_2d[1][2]                               

63

In [6]:
arr_2d[1,2]

63

In [7]:
arr_2d[2,2]

96

In [8]:
arr_2d[:1, 1:2]

array([[566]])

In [9]:
arr_2d[1:, :2]

array([[ 44,  65],
       [723, 843]])

In [10]:
arr_2d[:2, :2]

array([[ 34, 566],
       [ 44,  65]])

In [11]:
arr_2d[1:2, :]

array([[44, 65, 63, 78, 56]])

In [12]:
arr_2d[:]

array([[ 34, 566, 790,  78,  90],
       [ 44,  65,  63,  78,  56],
       [723, 843,  96,  10,  90]])

In [13]:
arr_2d[1:,1:]

array([[ 65,  63,  78,  56],
       [843,  96,  10,  90]])

In [14]:
arr_2d[:2,:]

array([[ 34, 566, 790,  78,  90],
       [ 44,  65,  63,  78,  56]])

In [15]:
aar = np.arange(1,11)
aar

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [16]:
bool_arr = aar>5

In [17]:
bool_arr

array([False, False, False, False, False,  True,  True,  True,  True,
        True])

In [18]:
aar[bool_arr]

array([ 6,  7,  8,  9, 10])

In [19]:
aar[aar>2]

array([ 3,  4,  5,  6,  7,  8,  9, 10])

In [20]:
aar[aar<5]

array([1, 2, 3, 4])

In [21]:
arr_5d = np.arange(50).reshape(5,10)

In [22]:
arr_5d

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [23]:
arr_5d[1:, 1:3]

array([[11, 12],
       [21, 22],
       [31, 32],
       [41, 42]])

In [24]:
arr_5d[3:, 6:8]

array([[36, 37],
       [46, 47]])

# Array Operations.

In [25]:
brr = np.arange(1,11)
brr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [26]:
brr + brr

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [27]:
brr - brr

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [28]:
brr * brr

array([  1,   4,   9,  16,  25,  36,  49,  64,  81, 100])

In [29]:
brr / brr

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [30]:
brr + 100

array([101, 102, 103, 104, 105, 106, 107, 108, 109, 110])

In [31]:
np.sqrt(brr)

array([1.        , 1.41421356, 1.73205081, 2.        , 2.23606798,
       2.44948974, 2.64575131, 2.82842712, 3.        , 3.16227766])

In [32]:
brr ** 2

array([  1,   4,   9,  16,  25,  36,  49,  64,  81, 100])

In [33]:
np.exp(brr)

array([2.71828183e+00, 7.38905610e+00, 2.00855369e+01, 5.45981500e+01,
       1.48413159e+02, 4.03428793e+02, 1.09663316e+03, 2.98095799e+03,
       8.10308393e+03, 2.20264658e+04])

In [34]:
brr.max()

10

In [35]:
np.sin(brr)

array([ 0.84147098,  0.90929743,  0.14112001, -0.7568025 , -0.95892427,
       -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849, -0.54402111])

In [36]:
np.random.randn(25)

array([-0.9144115 ,  1.54189371,  1.12838035, -0.24606549, -0.03386648,
       -0.50317997,  0.45679895, -0.8032572 , -1.32859842, -1.0547202 ,
        1.34393405, -0.29561261,  0.25824479,  0.62480449, -0.6079935 ,
        0.07809456,  0.63899629,  0.4091041 , -0.4063975 ,  0.75643572,
        0.09351874, -0.79567808,  0.04531286, -0.19585283, -1.1482918 ])

In [37]:
np.linspace(0,1,20)

array([0.        , 0.05263158, 0.10526316, 0.15789474, 0.21052632,
       0.26315789, 0.31578947, 0.36842105, 0.42105263, 0.47368421,
       0.52631579, 0.57894737, 0.63157895, 0.68421053, 0.73684211,
       0.78947368, 0.84210526, 0.89473684, 0.94736842, 1.        ])

In [38]:
mat = np.arange(1,26).reshape(5,5)
mat

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [39]:
mat[2:, 1:]

array([[12, 13, 14, 15],
       [17, 18, 19, 20],
       [22, 23, 24, 25]])

In [40]:
crr = mat[3:4, 4]
crr[0]

20

In [41]:
mat[0:3,1:2]

array([[ 2],
       [ 7],
       [12]])

In [42]:
mat[4, :]

array([21, 22, 23, 24, 25])

In [43]:
mat[3:, :]

array([[16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [44]:
np.sum(mat)


325

In [45]:
col = np.sum(mat, axis = 0)

In [46]:
col

array([55, 60, 65, 70, 75])

In [47]:
np.std(mat, dtype = np.float64)

7.211102550927978

In [48]:
np.std(mat)

7.211102550927978

In [49]:
c = np.linspace(0,1,11)
c


array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1. ])

In [50]:
np.arange(1,101).reshape(10,10)/100

array([[0.01, 0.02, 0.03, 0.04, 0.05, 0.06, 0.07, 0.08, 0.09, 0.1 ],
       [0.11, 0.12, 0.13, 0.14, 0.15, 0.16, 0.17, 0.18, 0.19, 0.2 ],
       [0.21, 0.22, 0.23, 0.24, 0.25, 0.26, 0.27, 0.28, 0.29, 0.3 ],
       [0.31, 0.32, 0.33, 0.34, 0.35, 0.36, 0.37, 0.38, 0.39, 0.4 ],
       [0.41, 0.42, 0.43, 0.44, 0.45, 0.46, 0.47, 0.48, 0.49, 0.5 ],
       [0.51, 0.52, 0.53, 0.54, 0.55, 0.56, 0.57, 0.58, 0.59, 0.6 ],
       [0.61, 0.62, 0.63, 0.64, 0.65, 0.66, 0.67, 0.68, 0.69, 0.7 ],
       [0.71, 0.72, 0.73, 0.74, 0.75, 0.76, 0.77, 0.78, 0.79, 0.8 ],
       [0.81, 0.82, 0.83, 0.84, 0.85, 0.86, 0.87, 0.88, 0.89, 0.9 ],
       [0.91, 0.92, 0.93, 0.94, 0.95, 0.96, 0.97, 0.98, 0.99, 1.  ]])

In [51]:
np.random.rand(1)

array([0.22322399])